module.exports = [
    {
        home: "MI",
        away: "CSK",
        fixture: "7/4,8"
    }, {
        home: "DD",
        away: "KXI",
        fixture: "8/4,4"
    }, {
        home: "KKR",
        away: "RCB",
        fixture: "8/4,8"
    }, {
        home: "SRH",
        away: "RR",
        fixture: "9/4,8"
    }, {
        home: "CSK",
        away: "KKR",
        fixture: "10/4,8"
    }, {
        home: "RR",
        away: "DD",
        fixture: "11/4,8"
    }, {
        home: "SRH",
        away: "MI",
        fixture: "12/4,8"
    }, {
        home: "RCB",
        away: "KXI",
        fixture: "13/4,8"
    }, {
        home: "MI",
        away: "DD",
        fixture: "14/4,4"
    }, {
        home: "KKR",
        away: "SRH",
        fixture: "14/4,8"
    }, {
        home: "RCB",
        away: "RR",
        fixture: "15/4,4"
    }, {
        home: "KXI",
        away: "CSK",
        fixture: "15/4,8"
    }, {
        home: "KKR",
        away: "DD",
        fixture: "16/4,8"
    }, {
        home: "MI",
        away: "RCB",
        fixture: "17/4,8"
    }, {
        home: "RR",
        away: "KKR",
        fixture: "18/4,8"
    }, {
        home: "KXI",
        away: "SRH",
        fixture: "19/4,8"
    }, {
        home: "CSK",
        away: "RR",
        fixture: "20/4,8"
    }, {
        home: "KKR",
        away: "KXI",
        fixture: "21/4,4"
    }, {
        home: "DD",
        away: "RCB",
        fixture: "21/4,8"
    }, {
        home: "SRH",
        away: "CSK",
        fixture: "22/4,4"
    }, {
        home: "RR",
        away: "MI",
        fixture: "22/4,8"
    }, {
        home: "DD",
        away: "KXI",
        fixture: "23/4,8"
    }, {
        home: "MI",
        away: "SRH",
        fixture: "24/4,8"
    }, {
        home: "RCB",
        away: "CSK",
        fixture: "25/4,8"
    }, {
        home: "SRH",
        away: "KXI",
        fixture: "26/4,8"
    }, {
        home: "DD",
        away: "KKR",
        fixture: "27/4,8"
    }, {
        home: "CSK",
        away: "MI",
        fixture: "28/4,8"
    }, {
        home: "RR",
        away: "SRH",
        fixture: "29/4,4"
    }, {
        home: "RCB",
        away: "KKR",
        fixture: "29/4,8"
    }, {
        home: "CSK",
        away: "DD",
        fixture: "30/4,8"
    }, {
        home: "RCB",
        away: "MI",
        fixture: "1/5,8"
    }, {
        home: "DD",
        away: "RR",
        fixture: "2/5,8"
    }, {
        home: "KKR",
        away: "CSK",
        fixture: "3/5,8"
    }, {
        home: "KXI",
        away: "MI",
        fixture: "4/5,8"
    }, {
        home: "CSK",
        away: "RCB",
        fixture: "5/5,4"
    }, {
        home: "SRH",
        away: "DD",
        fixture: "5/5,8"
    }, {
        home: "MI",
        away: "KKR",
        fixture: "6/5,4"
    }, {
        home: "KXI",
        away: "RR",
        fixture: "6/5,8"
    }, {
        home: "SRH",
        away: "RCB",
        fixture: "7/5,4"
    }, {
        home: "RR",
        away: "KXI",
        fixture: "8/5,8"
    }, {
        home: "KKR",
        away: "MI",
        fixture: "9/5,8"
    }, {
        home: "DD",
        away: "SRH",
        fixture: "10/5,8"
    }, {
        home: "RR",
        away: "CSK",
        fixture: "11/5,8"
    }, {
        home: "KXI",
        away: "KKR",
        fixture: "12/5,4"
    }, {
        home: "RCB",
        away: "DD",
        fixture: "12/5,8"
    }, {
        home: "CSK",
        away: "SRH",
        fixture: "13/5,4"
    }, {
        home: "MI",
        away: "RR",
        fixture: "13/5,8"
    }, {
        home: "KXI",
        away: "RCB",
        fixture: "14/5,8"
    }, {
        home: "KKR",
        away: "RR",
        fixture: "15/5,8"
    }, {
        home: "MI",
        away: "KXI",
        fixture: "16/5,8"
    }, {
        home: "RCB",
        away: "SRH",
        fixture: "17/5,8"
    }, {
        home: "DD",
        away: "CSK",
        fixture: "18/5,8"
    }, {
        home: "RR",
        away: "RCB",
        fixture: "19/5,4"
    }, {
        home: "SRH",
        away: "KKR",
        fixture: "19/5,8"
    }, {
        home: "DD",
        away: "MI",
        fixture: "20/5,4"
    }, {
        home: "CSK",
        away: "KXI",
        fixture: "20/5,8"
    }, {
        home: "TBC",
        away: "TBC",
        fixture: "22/5,8"
    }, {
        home: "TBC",
        away: "TBC",
        fixture: "23/5,8"
    }, {
        home: "TBC",
        away: "TBC",
        fixture: "25/5,8"
    }, {
        home: "TBC",
        away: "TBC",
        fixture: "27/5,8"
    }
];
